//
// EventSalaryCompactView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct EventSalaryCompactView: Codable {

    public var eventId: UUID?
    public var count: Int?
    public var _description: String?

    public init(eventId: UUID? = nil, count: Int? = nil, _description: String? = nil) {
        self.eventId = eventId
        self.count = count
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey {
        case eventId
        case count
        case _description = "description"
    }

}
