//
// EventSalaryFullView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct EventSalaryFullView: Codable {

    public var eventId: UUID?
    public var created: Date?
    public var shiftSalaries: [ShiftSalaryView]?
    public var placeSalaries: [PlaceSalaryView]?
    public var authorId: UUID?
    public var modificationDate: Date?
    public var count: Int?
    public var _description: String?

    public init(eventId: UUID? = nil, created: Date? = nil, shiftSalaries: [ShiftSalaryView]? = nil, placeSalaries: [PlaceSalaryView]? = nil, authorId: UUID? = nil, modificationDate: Date? = nil, count: Int? = nil, _description: String? = nil) {
        self.eventId = eventId
        self.created = created
        self.shiftSalaries = shiftSalaries
        self.placeSalaries = placeSalaries
        self.authorId = authorId
        self.modificationDate = modificationDate
        self.count = count
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey {
        case eventId
        case created
        case shiftSalaries
        case placeSalaries
        case authorId
        case modificationDate
        case count
        case _description = "description"
    }

}
