//
// EventSalaryCreateEdit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EventSalaryCreateEdit: Codable {

    public var shiftSalaries: [ShiftSalaryEdit]?
    public var placeSalaries: [PlaceSalaryEdit]?
    public var count: Int?
    public var _description: String?

    public init(shiftSalaries: [ShiftSalaryEdit]? = nil, placeSalaries: [PlaceSalaryEdit]? = nil, count: Int? = nil, _description: String? = nil) {
        self.shiftSalaries = shiftSalaries
        self.placeSalaries = placeSalaries
        self.count = count
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case shiftSalaries
        case placeSalaries
        case count
        case _description = "description"
    }

}
