//
// ReportUserSalaryEdit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct ReportUserSalaryEdit: Codable {

    public var count: Int?
    public var _description: String?

    public init(count: Int? = nil, _description: String? = nil) {
        self.count = count
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey {
        case count
        case _description = "description"
    }

}
