//
// ShiftSalaryEdit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ShiftSalaryEdit: Codable {

    public var shiftId: UUID?
    public var count: Int?
    public var _description: String?

    public init(shiftId: UUID? = nil, count: Int? = nil, _description: String? = nil) {
        self.shiftId = shiftId
        self.count = count
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case shiftId
        case count
        case _description = "description"
    }

}
