//
// EquipmentAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class EquipmentAPI {
    /**

     - parameter eventId: (query)  (optional)
     - parameter equipmentTypeId: (query)  (optional)
     - parameter match: (query)  (optional)
     - parameter all: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEquipmentGet(eventId: UUID? = nil, equipmentTypeId: UUID? = nil, match: String? = nil, all: Bool? = nil, completion: @escaping ((_ data: [CompactEquipmentView]?,_ error: Error?) -> Void)) {
        apiEquipmentGetWithRequestBuilder(eventId: eventId, equipmentTypeId: equipmentTypeId, match: match, all: all).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/Equipment
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "number" : 0,
  "equipmentTypeId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "serialNumber" : "serialNumber",
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "ownerId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "equipmentType" : {
    "rootId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "description" : "description",
    "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "shortTitle" : "shortTitle",
    "title" : "title",
    "parentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
  },
  "parentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
}, {
  "number" : 0,
  "equipmentTypeId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "serialNumber" : "serialNumber",
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "ownerId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "equipmentType" : {
    "rootId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "description" : "description",
    "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "shortTitle" : "shortTitle",
    "title" : "title",
    "parentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
  },
  "parentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
} ]}]
     - parameter eventId: (query)  (optional)
     - parameter equipmentTypeId: (query)  (optional)
     - parameter match: (query)  (optional)
     - parameter all: (query)  (optional)

     - returns: RequestBuilder<[CompactEquipmentView]> 
     */
    open class func apiEquipmentGetWithRequestBuilder(eventId: UUID? = nil, equipmentTypeId: UUID? = nil, match: String? = nil, all: Bool? = nil) -> RequestBuilder<[CompactEquipmentView]> {
        let path = "/api/Equipment"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "eventId": eventId, 
                        "equipmentTypeId": equipmentTypeId, 
                        "match": match, 
                        "all": all
        ])


        let requestBuilder: RequestBuilder<[CompactEquipmentView]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEquipmentIdGet(_id: UUID, completion: @escaping ((_ data: EquipmentView?,_ error: Error?) -> Void)) {
        apiEquipmentIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/Equipment/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "number" : 0,
  "equipmentTypeId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "serialNumber" : "serialNumber",
  "children" : [ null, null ],
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "ownerId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "equipmentType" : {
    "rootId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "description" : "description",
    "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "shortTitle" : "shortTitle",
    "title" : "title",
    "parentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
  },
  "parentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<EquipmentView> 
     */
    open class func apiEquipmentIdGetWithRequestBuilder(_id: UUID) -> RequestBuilder<EquipmentView> {
        var path = "/api/Equipment/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<EquipmentView>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Create new Equipment

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEquipmentPost(body: EquipmentCreateRequest? = nil, completion: @escaping ((_ data: EquipmentView?,_ error: Error?) -> Void)) {
        apiEquipmentPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create new Equipment
     - POST /api/Equipment
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "number" : 0,
  "equipmentTypeId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "serialNumber" : "serialNumber",
  "children" : [ null, null ],
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "ownerId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "equipmentType" : {
    "rootId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "description" : "description",
    "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "shortTitle" : "shortTitle",
    "title" : "title",
    "parentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
  },
  "parentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<EquipmentView> 
     */
    open class func apiEquipmentPostWithRequestBuilder(body: EquipmentCreateRequest? = nil) -> RequestBuilder<EquipmentView> {
        let path = "/api/Equipment"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<EquipmentView>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**
     Edit equipment

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEquipmentPut(body: EquipmentEditRequest? = nil, completion: @escaping ((_ data: EquipmentView?,_ error: Error?) -> Void)) {
        apiEquipmentPutWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Edit equipment
     - PUT /api/Equipment
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "number" : 0,
  "equipmentTypeId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "serialNumber" : "serialNumber",
  "children" : [ null, null ],
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "ownerId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "equipmentType" : {
    "rootId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "description" : "description",
    "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "shortTitle" : "shortTitle",
    "title" : "title",
    "parentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
  },
  "parentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<EquipmentView> 
     */
    open class func apiEquipmentPutWithRequestBuilder(body: EquipmentEditRequest? = nil) -> RequestBuilder<EquipmentView> {
        let path = "/api/Equipment"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<EquipmentView>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
