//
// EventTypeAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire

open class EventTypeAPI {
    /**

     - parameter match: (query)  (optional)
     - parameter all: (query)  (optional, default to false)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEventTypeGet(match: String? = nil, all: Bool? = nil, completion: @escaping ((_ data: [EventTypeView]?, _ error: Error?) -> Void)) {
        apiEventTypeGetWithRequestBuilder(match: match, all: all).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     - GET /api/EventType
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "title" : "title"
}, {
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "title" : "title"
} ]}]
     - parameter match: (query)  (optional)
     - parameter all: (query)  (optional, default to false)

     - returns: RequestBuilder<[EventTypeView]> 
     */
    open class func apiEventTypeGetWithRequestBuilder(match: String? = nil, all: Bool? = nil) -> RequestBuilder<[EventTypeView]> {
        let path = "/api/EventType"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String: Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "match": match,
                        "all": all
        ])

        let requestBuilder: RequestBuilder<[EventTypeView]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEventTypeIdGet(_id: UUID, completion: @escaping ((_ data: EventTypeView?, _ error: Error?) -> Void)) {
        apiEventTypeIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     - GET /api/EventType/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "title" : "title"
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<EventTypeView> 
     */
    open class func apiEventTypeIdGetWithRequestBuilder(_id: UUID) -> RequestBuilder<EventTypeView> {
        var path = "/api/EventType/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String: Any]? = nil
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<EventTypeView>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEventTypePost(body: EventTypeCreateRequest? = nil, completion: @escaping ((_ data: EventTypeView?, _ error: Error?) -> Void)) {
        apiEventTypePostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     - POST /api/EventType
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "title" : "title"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<EventTypeView> 
     */
    open class func apiEventTypePostWithRequestBuilder(body: EventTypeCreateRequest? = nil) -> RequestBuilder<EventTypeView> {
        let path = "/api/EventType"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<EventTypeView>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEventTypePut(body: EventTypeEditRequest? = nil, completion: @escaping ((_ data: EventTypeView?, _ error: Error?) -> Void)) {
        apiEventTypePutWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     - PUT /api/EventType
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "title" : "title"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<EventTypeView> 
     */
    open class func apiEventTypePutWithRequestBuilder(body: EventTypeEditRequest? = nil) -> RequestBuilder<EventTypeView> {
        let path = "/api/EventType"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<EventTypeView>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
