//
// UserPropertyAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire

open class UserPropertyAPI {
    /**
     Return all users properties

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiAccountPropertyGet(completion: @escaping ((_ data: [UserPropertyView]?, _ error: Error?) -> Void)) {
        apiAccountPropertyGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Return all users properties
     - GET /api/account/property
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "userPropertyType" : {
    "isLocked" : true,
    "instancesCount" : 0,
    "description" : "description",
    "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "title" : "title"
  },
  "value" : "value",
  "status" : "status"
}, {
  "userPropertyType" : {
    "isLocked" : true,
    "instancesCount" : 0,
    "description" : "description",
    "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "title" : "title"
  },
  "value" : "value",
  "status" : "status"
} ]}]

     - returns: RequestBuilder<[UserPropertyView]> 
     */
    open class func apiAccountPropertyGetWithRequestBuilder() -> RequestBuilder<[UserPropertyView]> {
        let path = "/api/account/property"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String: Any]? = nil
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[UserPropertyView]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Edit property

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiAccountPropertyPut(body: UserPropertyEditRequest? = nil, completion: @escaping ((_ data: UserPropertyView?, _ error: Error?) -> Void)) {
        apiAccountPropertyPutWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Edit property
     - PUT /api/account/property
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "userPropertyType" : {
    "isLocked" : true,
    "instancesCount" : 0,
    "description" : "description",
    "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "title" : "title"
  },
  "value" : "value",
  "status" : "status"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<UserPropertyView> 
     */
    open class func apiAccountPropertyPutWithRequestBuilder(body: UserPropertyEditRequest? = nil) -> RequestBuilder<UserPropertyView> {
        let path = "/api/account/property"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<UserPropertyView>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
