//
// UserPropertyTypeAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class UserPropertyTypeAPI {
    /**
     Returns all user property types

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiAccountPropertyTypeGet(completion: @escaping ((_ data: [UserPropertyTypeView]?,_ error: Error?) -> Void)) {
        apiAccountPropertyTypeGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Returns all user property types
     - GET /api/account/property/type
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "isLocked" : true,
  "instancesCount" : 0,
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "title" : "title"
}, {
  "isLocked" : true,
  "instancesCount" : 0,
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "title" : "title"
} ]}]

     - returns: RequestBuilder<[UserPropertyTypeView]> 
     */
    open class func apiAccountPropertyTypeGetWithRequestBuilder() -> RequestBuilder<[UserPropertyTypeView]> {
        let path = "/api/account/property/type"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[UserPropertyTypeView]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Delete user property type

     - parameter _id: (path) Id of property type to delete 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiAccountPropertyTypeIdDelete(_id: UUID, completion: @escaping ((_ data: UUID?,_ error: Error?) -> Void)) {
        apiAccountPropertyTypeIdDeleteWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Delete user property type
     - DELETE /api/account/property/type/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example="046b6c7f-0b8a-43b9-b35d-6489e6daee91"}]
     - parameter _id: (path) Id of property type to delete 

     - returns: RequestBuilder<UUID> 
     */
    open class func apiAccountPropertyTypeIdDeleteWithRequestBuilder(_id: UUID) -> RequestBuilder<UUID> {
        var path = "/api/account/property/type/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UUID>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Returns one user property type by id

     - parameter _id: (path) Id of user property type 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiAccountPropertyTypeIdGet(_id: UUID, completion: @escaping ((_ data: UserPropertyTypeView?,_ error: Error?) -> Void)) {
        apiAccountPropertyTypeIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Returns one user property type by id
     - GET /api/account/property/type/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "isLocked" : true,
  "instancesCount" : 0,
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "title" : "title"
}}]
     - parameter _id: (path) Id of user property type 

     - returns: RequestBuilder<UserPropertyTypeView> 
     */
    open class func apiAccountPropertyTypeIdGetWithRequestBuilder(_id: UUID) -> RequestBuilder<UserPropertyTypeView> {
        var path = "/api/account/property/type/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UserPropertyTypeView>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Edit user property type

     - parameter _id: (path) Id of property type to delete 
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiAccountPropertyTypeIdPut(_id: UUID, body: UserPropertyTypeEditRequest? = nil, completion: @escaping ((_ data: UUID?,_ error: Error?) -> Void)) {
        apiAccountPropertyTypeIdPutWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Edit user property type
     - PUT /api/account/property/type/{id}
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example="046b6c7f-0b8a-43b9-b35d-6489e6daee91"}]
     - parameter _id: (path) Id of property type to delete 
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<UUID> 
     */
    open class func apiAccountPropertyTypeIdPutWithRequestBuilder(_id: UUID, body: UserPropertyTypeEditRequest? = nil) -> RequestBuilder<UUID> {
        var path = "/api/account/property/type/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UUID>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**
     Add new property type

     - parameter body: (body) Data with needed user property type (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiAccountPropertyTypePost(body: UserPropertyTypeCreateRequest? = nil, completion: @escaping ((_ data: UserPropertyTypeView?,_ error: Error?) -> Void)) {
        apiAccountPropertyTypePostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Add new property type
     - POST /api/account/property/type
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "isLocked" : true,
  "instancesCount" : 0,
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "title" : "title"
}}]
     - parameter body: (body) Data with needed user property type (optional)

     - returns: RequestBuilder<UserPropertyTypeView> 
     */
    open class func apiAccountPropertyTypePostWithRequestBuilder(body: UserPropertyTypeCreateRequest? = nil) -> RequestBuilder<UserPropertyTypeView> {
        let path = "/api/account/property/type"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UserPropertyTypeView>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
