//
// VkPropertyAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class VkPropertyAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiAccountPropertyVkGet(completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        apiAccountPropertyVkGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/account/property/vk
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=""}]

     - returns: RequestBuilder<String> 
     */
    open class func apiAccountPropertyVkGetWithRequestBuilder() -> RequestBuilder<String> {
        let path = "/api/account/property/vk"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiAccountPropertyVkPost(body: VkVerifyRequest? = nil, completion: @escaping ((_ data: UserView?,_ error: Error?) -> Void)) {
        apiAccountPropertyVkPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/account/property/vk
     - 

     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "firstName" : "firstName",
  "lastName" : "lastName",
  "phoneNumber" : "phoneNumber",
  "middleName" : "middleName",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "email" : "email",
  "properties" : [ {
    "userPropertyType" : {
      "isLocked" : true,
      "instancesCount" : 0,
      "description" : "description",
      "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
      "title" : "title"
    },
    "value" : "value",
    "status" : "status"
  }, {
    "userPropertyType" : {
      "isLocked" : true,
      "instancesCount" : 0,
      "description" : "description",
      "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
      "title" : "title"
    },
    "value" : "value",
    "status" : "status"
  } ]
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<UserView> 
     */
    open class func apiAccountPropertyVkPostWithRequestBuilder(body: VkVerifyRequest? = nil) -> RequestBuilder<UserView> {
        let path = "/api/account/property/vk"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UserView>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
