//
// AccountEditRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct AccountEditRequest: Codable {

    public var firstName: String?
    public var lastName: String?
    public var middleName: String?
    public var phoneNumber: String?

    public init(firstName: String?, lastName: String?, middleName: String?, phoneNumber: String?) {
        self.firstName = firstName
        self.lastName = lastName
        self.middleName = middleName
        self.phoneNumber = phoneNumber
    }

}
