//
// AccountCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct AccountCreateRequest: Codable {

    public var firstName: String
    public var lastName: String
    public var middleName: String
    public var password: String
    public var email: String
    public var accessToken: String
    public var phoneNumber: String?

    public init(firstName: String, lastName: String, middleName: String, password: String, email: String, accessToken: String, phoneNumber: String?) {
        self.firstName = firstName
        self.lastName = lastName
        self.middleName = middleName
        self.password = password
        self.email = email
        self.accessToken = accessToken
        self.phoneNumber = phoneNumber
    }

}
