//
// ChangePasswordRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChangePasswordRequest: Codable {

    public var currentPassword: String?
    public var newPassword: String?

    public init(currentPassword: String?, newPassword: String?) {
        self.currentPassword = currentPassword
        self.newPassword = newPassword
    }


}

