//
// CompactEquipmentView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct CompactEquipmentView: Codable {

    public var _id: UUID?
    public var serialNumber: String?
    public var _description: String?
    public var number: Int?
    public var equipmentTypeId: UUID?
    public var equipmentType: CompactEquipmentTypeView?
    public var ownerId: UUID?
    public var parentId: UUID?

    public init(_id: UUID?, serialNumber: String?, _description: String?, number: Int?, equipmentTypeId: UUID?, equipmentType: CompactEquipmentTypeView?, ownerId: UUID?, parentId: UUID?) {
        self._id = _id
        self.serialNumber = serialNumber
        self._description = _description
        self.number = number
        self.equipmentTypeId = equipmentTypeId
        self.equipmentType = equipmentType
        self.ownerId = ownerId
        self.parentId = parentId
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case serialNumber
        case _description = "description"
        case number
        case equipmentTypeId
        case equipmentType
        case ownerId
        case parentId
    }

}
