//
// CreateEditPlaceView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateEditPlaceView: Codable {

    public var _id: UUID?
    public var clientId: Int?
    public var targetParticipantsCount: Int?
    public var _description: String?
    public var equipment: [EquipmentView]?
    public var participants: [UserAndEventRole]?
    public var invited: [UserAndEventRole]?
    public var wishers: [UserAndEventRole]?
    public var unknowns: [UserAndEventRole]?

    public init(_id: UUID?, clientId: Int?, targetParticipantsCount: Int?, _description: String?, equipment: [EquipmentView]?, participants: [UserAndEventRole]?, invited: [UserAndEventRole]?, wishers: [UserAndEventRole]?, unknowns: [UserAndEventRole]?) {
        self._id = _id
        self.clientId = clientId
        self.targetParticipantsCount = targetParticipantsCount
        self._description = _description
        self.equipment = equipment
        self.participants = participants
        self.invited = invited
        self.wishers = wishers
        self.unknowns = unknowns
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case clientId
        case targetParticipantsCount
        case _description = "description"
        case equipment
        case participants
        case invited
        case wishers
        case unknowns
    }

}

