//
// EquipmentTypeEditRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EquipmentTypeEditRequest: Codable {

    public var title: String?
    public var shortTitle: String?
    public var _description: String?
    public var parentId: UUID?
    public var _id: UUID

    public init(title: String?, shortTitle: String?, _description: String?, parentId: UUID?, _id: UUID) {
        self.title = title
        self.shortTitle = shortTitle
        self._description = _description
        self.parentId = parentId
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case shortTitle
        case _description = "description"
        case parentId
        case _id = "id"
    }

}

