//
// EquipmentTypeCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EquipmentTypeCreateRequest: Codable {

    public var title: String
    public var shortTitle: String?
    public var _description: String?
    public var parentId: UUID?

    public init(title: String, shortTitle: String?, _description: String?, parentId: UUID?) {
        self.title = title
        self.shortTitle = shortTitle
        self._description = _description
        self.parentId = parentId
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case shortTitle
        case _description = "description"
        case parentId
    }

}

