//
// EventApplicationView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct EventApplicationView: Codable {

    public var _id: UUID?
    public var title: String?
    public var eventType: EventTypeView?
    public var beginTime: Date?
    public var placeId: UUID?
    public var placeDescription: String?
    public var placeNumber: Int?
    public var shiftDescription: String?
    public var shiftDurationInMinutes: Double?
    public var eventRole: EventRoleView?
    public var creationTime: Date?
    public var doneTime: Date?

    public init(_id: UUID?, title: String?, eventType: EventTypeView?, beginTime: Date?, placeId: UUID?, placeDescription: String?, placeNumber: Int?, shiftDescription: String?, shiftDurationInMinutes: Double?, eventRole: EventRoleView?, creationTime: Date?, doneTime: Date?) {
        self._id = _id
        self.title = title
        self.eventType = eventType
        self.beginTime = beginTime
        self.placeId = placeId
        self.placeDescription = placeDescription
        self.placeNumber = placeNumber
        self.shiftDescription = shiftDescription
        self.shiftDurationInMinutes = shiftDurationInMinutes
        self.eventRole = eventRole
        self.creationTime = creationTime
        self.doneTime = doneTime
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case title
        case eventType
        case beginTime
        case placeId
        case placeDescription
        case placeNumber
        case shiftDescription
        case shiftDurationInMinutes
        case eventRole
        case creationTime
        case doneTime
    }

}
