//
// EventTypeView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EventTypeView: Codable {

    public var _id: UUID?
    public var title: String?
    public var _description: String?

    public init(_id: UUID?, title: String?, _description: String?) {
        self._id = _id
        self.title = title
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case _description = "description"
    }

}

