//
// EventView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EventView: Codable {

    public var _id: UUID?
    public var title: String?
    public var _description: String?
    public var address: String?
    public var eventType: EventTypeView?
    public var shifts: [ShiftView]?

    public init(_id: UUID?, title: String?, _description: String?, address: String?, eventType: EventTypeView?, shifts: [ShiftView]?) {
        self._id = _id
        self.title = title
        self._description = _description
        self.address = address
        self.eventType = eventType
        self.shifts = shifts
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case _description = "description"
        case address
        case eventType
        case shifts
    }

}

