//
// EventEditRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EventEditRequest: Codable {

    public var title: String?
    public var _description: String?
    public var address: String?
    public var eventTypeId: UUID?
    public var shifts: [ShiftEditRequest]?
    public var _id: UUID

    public init(title: String?, _description: String?, address: String?, eventTypeId: UUID?, shifts: [ShiftEditRequest]?, _id: UUID) {
        self.title = title
        self._description = _description
        self.address = address
        self.eventTypeId = eventTypeId
        self.shifts = shifts
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case _description = "description"
        case address
        case eventTypeId
        case shifts
        case _id = "id"
    }

}

