//
// GetSummaryRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSummaryRequest: Codable {

    public var targetEventTypes: [UUID]?

    public init(targetEventTypes: [UUID]?) {
        self.targetEventTypes = targetEventTypes
    }


}

