//
// IdRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct IdRequest: Codable {

    public var _id: UUID

    public init(_id: UUID) {
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
    }

}
