//
// PersonWorkRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonWorkRequest: Codable {

    public var eventRoleId: UUID?
    public var delete: Bool?
    public var _id: UUID

    public init(eventRoleId: UUID?, delete: Bool?, _id: UUID) {
        self.eventRoleId = eventRoleId
        self.delete = delete
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case eventRoleId
        case delete
        case _id = "id"
    }

}

