//
// PlaceEditRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlaceEditRequest: Codable {

    public var clientId: Int?
    public var targetParticipantsCount: Int?
    public var equipment: [DeletableRequest]?
    public var invited: [PersonWorkRequest]?
    public var _description: String?
    public var delete: Bool?
    public var _id: UUID

    public init(clientId: Int?, targetParticipantsCount: Int?, equipment: [DeletableRequest]?, invited: [PersonWorkRequest]?, _description: String?, delete: Bool?, _id: UUID) {
        self.clientId = clientId
        self.targetParticipantsCount = targetParticipantsCount
        self.equipment = equipment
        self.invited = invited
        self._description = _description
        self.delete = delete
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case clientId
        case targetParticipantsCount
        case equipment
        case invited
        case _description = "description"
        case delete
        case _id = "id"
    }

}

