//
// PlaceCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlaceCreateRequest: Codable {

    public var clientId: Int?
    public var targetParticipantsCount: Int?
    public var equipment: [UUID]?
    public var invited: [PersonWorkRequest]?
    public var _description: String?

    public init(clientId: Int?, targetParticipantsCount: Int?, equipment: [UUID]?, invited: [PersonWorkRequest]?, _description: String?) {
        self.clientId = clientId
        self.targetParticipantsCount = targetParticipantsCount
        self.equipment = equipment
        self.invited = invited
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case clientId
        case targetParticipantsCount
        case equipment
        case invited
        case _description = "description"
    }

}

