//
// RequestResetPasswordRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct RequestResetPasswordRequest: Codable {

    public var email: String?
    public var redirectUrl: String?

    public init(email: String?, redirectUrl: String?) {
        self.email = email
        self.redirectUrl = redirectUrl
    }

}
