//
// ResetPasswordRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResetPasswordRequest: Codable {

    public var email: String?
    public var token: String?
    public var newPassword: String?

    public init(email: String?, token: String?, newPassword: String?) {
        self.email = email
        self.token = token
        self.newPassword = newPassword
    }


}

