//
// ShiftCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ShiftCreateRequest: Codable {

    public var clientId: Int?
    public var beginTime: Date?
    public var endTime: Date?
    public var places: [PlaceCreateRequest]?
    public var _description: String?

    public init(clientId: Int?, beginTime: Date?, endTime: Date?, places: [PlaceCreateRequest]?, _description: String?) {
        self.clientId = clientId
        self.beginTime = beginTime
        self.endTime = endTime
        self.places = places
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case clientId
        case beginTime
        case endTime
        case places
        case _description = "description"
    }

}

