//
// ShiftEditRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct ShiftEditRequest: Codable {

    public var clientId: Int?
    public var beginTime: Date?
    public var endTime: Date?
    public var places: [PlaceEditRequest]?
    public var _description: String?
    public var delete: Bool?
    public var _id: UUID

    public init(clientId: Int?, beginTime: Date?, endTime: Date?, places: [PlaceEditRequest]?, _description: String?, delete: Bool?, _id: UUID) {
        self.clientId = clientId
        self.beginTime = beginTime
        self.endTime = endTime
        self.places = places
        self._description = _description
        self.delete = delete
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey {
        case clientId
        case beginTime
        case endTime
        case places
        case _description = "description"
        case delete
        case _id = "id"
    }

}
