//
// UserView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct UserView: Codable {

    public var _id: UUID?
    public var firstName: String?
    public var lastName: String?
    public var middleName: String?
    public var phoneNumber: String?
    public var email: String?
    public var properties: [UserPropertyView]?

    public init(_id: UUID?, firstName: String?, lastName: String?, middleName: String?, phoneNumber: String?, email: String?, properties: [UserPropertyView]?) {
        self._id = _id
        self.firstName = firstName
        self.lastName = lastName
        self.middleName = middleName
        self.phoneNumber = phoneNumber
        self.email = email
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case firstName
        case lastName
        case middleName
        case phoneNumber
        case email
        case properties
    }
    
    public init() {}
}
