//
// UserSettingPresent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserSettingPresent: Codable {

//    public var title: String?
//    public var value: Any?
//
//    public init(title: String?, value: Any?) {
//        self.title = title
//        self.value = value
//    }
    
    
    public var title: String?

    public init(title: String?) {
        self.title = title
    }


}

