//
// UserAndEventRole.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserAndEventRole: Codable {

    public var user: UserView?
    public var eventRole: EventRoleView?
    public var creationTime: Date?
    public var doneTime: Date?

    public init(user: UserView?, eventRole: EventRoleView?, creationTime: Date?, doneTime: Date?) {
        self.user = user
        self.eventRole = eventRole
        self.creationTime = creationTime
        self.doneTime = doneTime
    }


}

