//
// UserPropertyView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserPropertyView: Codable {

    public var value: String?
    public var status: String?
    public var userPropertyType: UserPropertyTypeView?

    public init(value: String?, status: String?, userPropertyType: UserPropertyTypeView?) {
        self.value = value
        self.status = status
        self.userPropertyType = userPropertyType
    }


}

