//
// UserPropertyEditRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserPropertyEditRequest: Codable {

    public var value: String?
    public var _id: UUID

    public init(value: String?, _id: UUID) {
        self.value = value
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case value
        case _id = "id"
    }

}

