//
// UsersEventsView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UsersEventsView: Codable {

    public var _id: UUID?
    public var address: String?
    public var title: String?
    public var eventType: EventTypeView?
    public var beginTime: Date?
    public var role: EventRoleView?

    public init(_id: UUID?, address: String?, title: String?, eventType: EventTypeView?, beginTime: Date?, role: EventRoleView?) {
        self._id = _id
        self.address = address
        self.title = title
        self.eventType = eventType
        self.beginTime = beginTime
        self.role = role
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case address
        case title
        case eventType
        case beginTime
        case role
    }

}

