//
// VkVerifyRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct VkVerifyRequest: Codable {

    public var token: String?
    public var vkId: Int?

    public init(token: String?, vkId: Int?) {
        self.token = token
        self.vkId = vkId
    }

}
