//
// WisherEventView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct WisherEventView: Codable {

    public var _id: UUID?
    public var title: String?
    public var eventType: EventTypeView?
    public var beginTime: Date?
    public var placeId: UUID?
    public var placeDescription: String?
    public var shiftDescription: String?
    public var currentParticipantsCount: Int?
    public var targetParticipantsCount: Int?
    public var user: UserView?
    public var eventRole: EventRoleView?
    public var creationTime: Date?
    public var doneTime: Date?

    public init(_id: UUID?, title: String?, eventType: EventTypeView?, beginTime: Date?, placeId: UUID?, placeDescription: String?, shiftDescription: String?, currentParticipantsCount: Int?, targetParticipantsCount: Int?, user: UserView?, eventRole: EventRoleView?, creationTime: Date?, doneTime: Date?) {
        self._id = _id
        self.title = title
        self.eventType = eventType
        self.beginTime = beginTime
        self.placeId = placeId
        self.placeDescription = placeDescription
        self.shiftDescription = shiftDescription
        self.currentParticipantsCount = currentParticipantsCount
        self.targetParticipantsCount = targetParticipantsCount
        self.user = user
        self.eventRole = eventRole
        self.creationTime = creationTime
        self.doneTime = doneTime
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case title
        case eventType
        case beginTime
        case placeId
        case placeDescription
        case shiftDescription
        case currentParticipantsCount
        case targetParticipantsCount
        case user
        case eventRole
        case creationTime
        case doneTime
    }

}
